// Employee voice fragments — §19 pools, §65 quantities.
//
// A fragment is one sentence-sized beat. The composer builds a message by picking one fragment
// per structural slot, so 20 openings x 20 contexts x 22 reactions x 22 requests is the real
// content surface, not 84 lines. Conditions are what make a voice recognisable: openings gate on
// personality and style (HOW someone speaks), context/reaction/request gate on tags (WHAT
// happened). Gating both on tags would collapse every character into one voice.
//
// Slot discipline: a fragment whose `{slot}` the caller did not supply is dropped as ineligible
// (see isFragmentEligible), so the bulk of these carry no slots and the slotted ones are
// deliberately rare. Callers can supply: company, team, role, segment, area, weeks, sinceWeek,
// amount, rival, stage. The composer adds mem_week / mem_weeksAgo / mem_<fact> when a memory
// callback is selected.

import type { Fragment, FragmentLibrary } from '../types'

const openings: readonly Fragment[] = [
  {
    id: 'emp.op.need_to_talk',
    type: 'opening',
    text: 'We need to talk.',
    tags: ['concern', 'direct'],
    weight: 3,
    conditions: { personalityMin: { directness: 70 }, relationshipMax: { trust: 65 } },
  },
  {
    id: 'emp.op.few_minutes',
    type: 'opening',
    text: 'Hey — do you have a few minutes?',
    tags: ['concern', 'warm'],
    weight: 3,
    conditions: { personalityMin: { empathy: 60 }, relationshipMin: { trust: 50 } },
  },
  {
    id: 'emp.op.straight_with_you',
    type: 'opening',
    text: "I want to be straight with you about something.",
    tags: ['concern', 'direct'],
    weight: 3,
    conditions: { personalityMin: { directness: 60 } },
  },
  {
    id: 'emp.op.keep_it_short',
    type: 'opening',
    text: "I'll keep this short.",
    tags: ['concern', 'direct'],
    weight: 2,
    conditions: { styles: ['blunt', 'direct'] },
  },
  {
    id: 'emp.op.sitting_on_this',
    type: 'opening',
    text: "I've been sitting on this for a while, and I think I have to say it.",
    tags: ['concern'],
    weight: 3,
    conditions: { personalityMin: { patience: 55 } },
  },
  {
    id: 'emp.op.twenty_minutes',
    type: 'opening',
    text: "Could we find twenty minutes this week? I'd rather do this properly than over messages.",
    tags: ['concern', 'formal'],
    weight: 3,
    conditions: { styles: ['formal', 'cautious', 'analytical'] },
  },
  {
    id: 'emp.op.not_easy_message',
    type: 'opening',
    text: "This isn't an easy message to write.",
    tags: ['concern'],
    weight: 2,
    conditions: { personalityMax: { ego: 55 }, styles: ['warm', 'cautious', 'formal'] },
  },
  {
    id: 'emp.op.where_i_stand',
    type: 'opening',
    text: 'I need to understand where I stand.',
    tags: ['concern', 'status'],
    weight: 3,
    conditions: { personalityMin: { ambition: 65 } },
  },
  {
    id: 'emp.op.blunt_because',
    type: 'opening',
    text: "I'm going to be blunt, because I think you'd rather I was.",
    tags: ['concern', 'direct'],
    weight: 2,
    conditions: { styles: ['blunt'], relationshipMin: { trust: 55 } },
  },
  {
    id: 'emp.op.rather_hear_from_me',
    type: 'opening',
    text: "I'd rather you heard this from me than from someone else.",
    tags: ['concern', 'loyalty'],
    weight: 3,
    conditions: { personalityMin: { loyalty: 60 } },
  },
  {
    id: 'emp.op.before_bigger',
    type: 'opening',
    text: "I want to put something on the table before it turns into a bigger problem.",
    tags: ['concern', 'analysis'],
    weight: 3,
    conditions: { styles: ['analytical', 'direct', 'formal'] },
  },
  {
    id: 'emp.op.still_fixable',
    type: 'opening',
    text: "I want to raise this while it's still fixable.",
    tags: ['concern'],
    weight: 3,
    conditions: { personalityMin: { optimism: 55 } },
  },
  {
    id: 'emp.op.talk_myself_out',
    type: 'opening',
    text: "Before I talk myself out of it again — can we talk?",
    tags: ['concern'],
    weight: 2,
    conditions: { personalityMax: { patience: 45 } },
  },
  {
    id: 'emp.op.been_quiet',
    type: 'opening',
    text: "I've been quiet about this. That was probably a mistake.",
    tags: ['concern'],
    weight: 2,
    conditions: { styles: ['warm', 'cautious'] },
  },
  {
    id: 'emp.op.can_i_be_honest',
    type: 'opening',
    text: 'Can I be honest with you?',
    tags: ['concern', 'warm'],
    weight: 3,
    conditions: { relationshipMin: { trust: 45 }, personalityMin: { empathy: 45 } },
  },
  {
    id: 'emp.op.flagging_early',
    type: 'opening',
    text: 'Flagging something early rather than late.',
    tags: ['concern', 'analysis'],
    weight: 2,
    conditions: { relationshipMin: { trust: 60 }, styles: ['analytical', 'direct'] },
  },
  {
    id: 'emp.op.two_weeks_wording',
    type: 'opening',
    text: "I've spent two weeks trying to find a clean way to say this. There isn't one.",
    tags: ['concern'],
    weight: 2,
    conditions: { personalityMin: { patience: 60 } },
  },
  {
    id: 'emp.op.say_nothing_version',
    type: 'opening',
    text: "There's a version of this where I say nothing and get on with it. I don't think that's the right one.",
    tags: ['concern', 'analysis'],
    weight: 2,
    conditions: { personalityMin: { directness: 45 }, styles: ['analytical', 'formal', 'cautious'] },
  },
  { id: 'emp.op.on_my_mind', type: 'opening', text: "Something's been on my mind, and I'd rather raise it than let it sit.", tags: ['concern'], weight: 2 },
  { id: 'emp.op.quick_one', type: 'opening', text: 'Quick one, but not a small one.', tags: ['concern'], weight: 1 },
  { id: 'emp.op.wanted_to_flag', type: 'opening', text: 'I wanted to flag something with you directly.', tags: ['concern'], weight: 2 },
  { id: 'emp.op.time_this_week', type: 'opening', text: "Do you have time this week? There's something I want to work through with you.", tags: ['concern'], weight: 2 },
]

const contexts: readonly Fragment[] = [
  {
    id: 'emp.ctx.pace_since_week',
    type: 'context',
    text: "The team has been running at this pace since week {sinceWeek}, and it hasn't let up.",
    tags: ['workload'],
    weight: 3,
    conditions: { requiresTags: ['workload'] },
  },
  {
    id: 'emp.ctx.shipped_every_deadline',
    type: 'context',
    text: "We've hit every date this quarter. We've also lost every weekend doing it.",
    tags: ['workload'],
    weight: 3,
    conditions: { requiresTags: ['workload'] },
  },
  {
    id: 'emp.ctx.pace_costs_quality',
    type: 'context',
    text: "I'm not complaining about hard work. I'm telling you the pace has started costing us quality.",
    tags: ['workload', 'quality'],
    weight: 3,
    conditions: { requiresTags: ['workload'] },
  },
  {
    id: 'emp.ctx.exec_above_me',
    type: 'context',
    text: 'Bringing someone in above me changes what I thought I was working toward.',
    tags: ['exec_hire', 'promotion'],
    weight: 4,
    conditions: { requiresTags: ['exec_hire'] },
  },
  {
    id: 'emp.ctx.heard_like_everyone',
    type: 'context',
    text: 'I heard about the {role} hire the same way everyone else did.',
    tags: ['exec_hire', 'communication'],
    weight: 3,
    conditions: { requiresTags: ['exec_hire'] },
  },
  {
    id: 'emp.ctx.not_yet_answer',
    type: 'context',
    text: "The last time we talked about my scope, the answer was 'not yet'. I've done the work since then.",
    tags: ['promotion'],
    weight: 3,
    conditions: { requiresTags: ['promotion'] },
  },
  {
    id: 'emp.ctx.market_pay',
    type: 'context',
    text: "I know what the market pays for this job right now. We're not close.",
    tags: ['compensation'],
    weight: 3,
    conditions: { requiresTags: ['compensation'] },
  },
  {
    id: 'emp.ctx.discount_bet',
    type: 'context',
    text: 'I took this job at a discount because I believed in the outcome. That was a bet, not a permanent arrangement.',
    tags: ['compensation', 'equity'],
    weight: 3,
    conditions: { requiresTags: ['compensation'] },
  },
  {
    id: 'emp.ctx.changed_twice',
    type: 'context',
    text: "We've changed what we're optimising for twice this quarter. My team can feel it.",
    tags: ['strategy'],
    weight: 3,
    conditions: { requiresTags: ['strategy'] },
  },
  {
    id: 'emp.ctx.segment_not_free',
    type: 'context',
    text: "I don't think we're wrong to chase {segment}. I think we're wrong to pretend it's free.",
    tags: ['strategy'],
    weight: 3,
    conditions: { requiresTags: ['strategy'] },
  },
  {
    id: 'emp.ctx.nobody_said_so',
    type: 'context',
    text: 'The response worked. Nobody has said so out loud.',
    tags: ['recognition'],
    weight: 3,
    conditions: { requiresTags: ['recognition'] },
  },
  {
    id: 'emp.ctx.recruiters_ignored',
    type: 'context',
    text: "I've had recruiters in my inbox all quarter. I've ignored them. I'm telling you that because it's still true today.",
    tags: ['departure_risk'],
    weight: 4,
    conditions: { requiresTags: ['departure_risk'] },
  },
  {
    id: 'emp.ctx.twice_the_size',
    type: 'context',
    text: '{company} is twice the size it was when I joined, and the way we make decisions has not changed at all.',
    tags: ['growth', 'process'],
    weight: 3,
    conditions: { requiresTags: ['growth'] },
  },
  {
    id: 'emp.ctx.after_cuts',
    type: 'context',
    text: 'We asked people to carry more after the cuts. They did it. They are finished.',
    tags: ['layoff', 'workload'],
    weight: 4,
    conditions: { requiresTags: ['layoff'] },
  },
  {
    id: 'emp.ctx.outage_cleanup',
    type: 'context',
    text: 'We spent {weeks} weeks cleaning up after the outage and shipped nothing else in that time.',
    tags: ['outage', 'crisis'],
    weight: 3,
    conditions: { requiresTags: ['outage'] },
  },
  {
    id: 'emp.ctx.raise_expectations',
    type: 'context',
    text: 'The raise changed the expectations on my team overnight. The headcount did not change with them.',
    tags: ['funding', 'workload'],
    weight: 3,
    conditions: { requiresTags: ['funding'] },
  },
  {
    id: 'emp.ctx.interviewing_closing_none',
    type: 'context',
    text: "I'm interviewing four people a week and closing none of them, and I think I know why.",
    tags: ['hiring'],
    weight: 3,
    conditions: { requiresTags: ['hiring'] },
  },
  {
    id: 'emp.ctx.month_of_triage',
    type: 'context',
    text: 'Everything I have done for a month has been triage.',
    tags: ['crisis', 'workload'],
    weight: 3,
    conditions: { requiresTags: ['crisis'] },
  },
  {
    id: 'emp.ctx.churn_visible',
    type: 'context',
    text: 'The customers we lost last month all told us the same thing on the way out.',
    tags: ['churn', 'product'],
    weight: 3,
    conditions: { requiresTags: ['churn'] },
  },
  {
    id: 'emp.ctx.rival_shipping',
    type: 'context',
    text: '{rival} shipped the thing we deprioritised, and my team noticed before I did.',
    tags: ['rival', 'product'],
    weight: 3,
    conditions: { requiresTags: ['rival'] },
  },
  { id: 'emp.ctx.not_new', type: 'context', text: "None of this is new. It's finally just loud enough that I can't work around it.", tags: ['concern'], weight: 2 },
  {
    id: 'emp.ctx.joined_for_problem',
    type: 'context',
    text: "I didn't join for a title. I joined because the problem was worth it. That part is still true.",
    tags: ['mission'],
    weight: 2,
    conditions: { motivations: ['mission'] },
  },
  { id: 'emp.ctx.team_asks_me', type: 'context', text: 'My team asks me what the plan is. I have stopped having a good answer.', tags: ['strategy', 'leadership'], weight: 2 },
]

const memoryCallbacks: readonly Fragment[] = [
  {
    id: 'emp.mem.promised_lead',
    type: 'memory',
    text: "In week {mem_week} you told me I'd have the opportunity to lead {mem_role}.",
    tags: ['promise', 'leadership'],
    weight: 5,
    conditions: { requiresTags: ['promise'] },
  },
  {
    id: 'emp.mem.commitment_real',
    type: 'memory',
    text: "You made me a commitment in week {mem_week}. I've been treating it as real.",
    tags: ['promise'],
    weight: 4,
    conditions: { requiresTags: ['promise'] },
  },
  {
    id: 'emp.mem.reason_still_here',
    type: 'memory',
    text: "That conversation in week {mem_week} is a large part of why I'm still here.",
    tags: ['promise', 'loyalty'],
    weight: 3,
    conditions: { requiresTags: ['promise'], personalityMin: { loyalty: 55 } },
  },
  {
    id: 'emp.mem.thought_id_shown',
    type: 'memory',
    text: "After week {mem_week}, I thought I'd shown I could do this.",
    tags: ['recognition', 'success'],
    weight: 4,
    conditions: { requiresTags: ['recognition'] },
  },
  {
    id: 'emp.mem.stayed_when_wrong',
    type: 'memory',
    text: 'When it went wrong in week {mem_week}, I was one of the people who stayed.',
    tags: ['crisis', 'support'],
    weight: 4,
    conditions: { requiresTags: ['crisis'] },
  },
  {
    id: 'emp.mem.asked_and_waited',
    type: 'memory',
    text: 'I asked about this {mem_weeksAgo} weeks ago and was told to wait. I waited.',
    tags: ['rejection', 'promotion'],
    weight: 4,
    conditions: { requiresTags: ['rejection'] },
  },
  {
    id: 'emp.mem.let_it_go_once',
    type: 'memory',
    text: "We didn't agree in week {mem_week} and I let it go. I'm less willing to let it go twice.",
    tags: ['conflict'],
    weight: 4,
    conditions: { requiresTags: ['conflict'] },
  },
  {
    id: 'emp.mem.backed_me',
    type: 'memory',
    text: "You backed me in week {mem_week} when it would have been easier not to. I haven't forgotten it.",
    tags: ['support'],
    weight: 4,
    conditions: { requiresTags: ['support'] },
  },
  {
    id: 'emp.mem.already_decided',
    type: 'memory',
    text: 'In week {mem_week} I found out the decision had already been made. That is the part that stayed with me.',
    tags: ['betrayal', 'communication'],
    weight: 5,
    conditions: { requiresTags: ['betrayal'] },
  },
  {
    id: 'emp.mem.told_my_team',
    type: 'memory',
    text: 'In week {mem_week} I sat in a room and told my team it was over. I did that for you.',
    tags: ['layoff'],
    weight: 5,
    conditions: { requiresTags: ['layoff'] },
  },
  {
    id: 'emp.mem.recruited_on_that',
    type: 'memory',
    text: 'I recruited half this team on the strength of what I told them in week {mem_week}.',
    tags: ['hire', 'promise'],
    weight: 3,
    conditions: { requiresTags: ['hire'] },
  },
  {
    id: 'emp.mem.scope_unchanged',
    type: 'memory',
    text: 'The last time my scope changed was week {mem_week}. Nothing since.',
    tags: ['promotion'],
    weight: 4,
    conditions: { requiresTags: ['promotion'] },
  },
  {
    id: 'emp.mem.week_i_learned',
    type: 'memory',
    text: 'I keep coming back to week {mem_week}.',
    tags: ['callback'],
    weight: 1,
  },
]

const reactions: readonly Fragment[] = [
  {
    id: 'emp.re.where_i_fit',
    type: 'reaction',
    text: 'It makes me question where I fit here.',
    tags: ['doubt'],
    weight: 4,
    conditions: { personalityMin: { ambition: 45 } },
  },
  {
    id: 'emp.re.recalibrating',
    type: 'reaction',
    text: "I'm not angry. I'm recalibrating.",
    tags: ['doubt'],
    weight: 3,
    conditions: { styles: ['analytical', 'formal'] },
  },
  {
    id: 'emp.re.explain_to_team',
    type: 'reaction',
    text: "Right now I'd struggle to explain to my team why this is the right call.",
    tags: ['leadership', 'doubt'],
    weight: 4,
    conditions: { personalityMin: { loyalty: 50 } },
  },
  {
    id: 'emp.re.no_confidence',
    type: 'reaction',
    text: "It reads as a vote of no confidence, and I would like to be wrong about that.",
    tags: ['doubt', 'status'],
    weight: 3,
    conditions: { personalityMin: { ego: 55 } },
  },
  {
    id: 'emp.re.how_i_found_out',
    type: 'reaction',
    text: "I can live with the decision. I can't live with how I found out.",
    tags: ['communication', 'trust'],
    weight: 4,
    conditions: { personalityMin: { directness: 55 } },
  },
  {
    id: 'emp.re.it_stung',
    type: 'reaction',
    text: 'If I am honest, it stung.',
    tags: ['doubt'],
    weight: 3,
    conditions: { personalityMin: { empathy: 55 }, personalityMax: { directness: 60 } },
  },
  {
    id: 'emp.re.answering_recruiters',
    type: 'reaction',
    text: "I've started answering the recruiter emails. I'd rather tell you that than not.",
    tags: ['departure_risk'],
    weight: 5,
    conditions: { relationshipMax: { trust: 70 } },
  },
  {
    id: 'emp.re.not_promising_six',
    type: 'reaction',
    text: "I'm not going anywhere this month. I'm not promising anything about the next six.",
    tags: ['departure_risk'],
    weight: 4,
    conditions: { personalityMin: { ambition: 55 } },
  },
  {
    id: 'emp.re.want_to_stay',
    type: 'reaction',
    text: 'I want to stay. I need a reason that is more than momentum.',
    tags: ['departure_risk', 'mission'],
    weight: 4,
    conditions: { personalityMin: { loyalty: 50 } },
  },
  {
    id: 'emp.re.job_either_way',
    type: 'reaction',
    text: 'I will keep doing the job either way. That is not the same as being fine.',
    tags: ['loyalty', 'doubt'],
    weight: 4,
    conditions: { personalityMin: { loyalty: 60 } },
  },
  {
    id: 'emp.re.patience_gone',
    type: 'reaction',
    text: 'It is hard to keep telling people to be patient when I have stopped being patient myself.',
    tags: ['leadership'],
    weight: 3,
    conditions: { personalityMax: { patience: 45 } },
  },
  {
    id: 'emp.re.solve_not_escalate',
    type: 'reaction',
    text: "I'd rather solve this than escalate it, which is why it is coming to you first.",
    tags: ['trust'],
    weight: 3,
    conditions: { relationshipMin: { trust: 60 } },
  },
  {
    id: 'emp.re.lose_two_people',
    type: 'reaction',
    text: 'I think we are one bad quarter from losing two of the best people here.',
    tags: ['departure_risk', 'team'],
    weight: 4,
    conditions: { personalityMin: { empathy: 55 } },
  },
  {
    id: 'emp.re.taken_seriously',
    type: 'reaction',
    text: 'The money is not the issue. Being taken seriously is.',
    tags: ['status', 'recognition'],
    weight: 4,
    conditions: { motivations: ['status', 'recognition'] },
  },
  {
    id: 'emp.re.money_is_the_issue',
    type: 'reaction',
    text: "The money is the issue, and I'd rather not dress it up as something else.",
    tags: ['compensation'],
    weight: 4,
    conditions: { motivations: ['money'], personalityMin: { directness: 55 } },
  },
  {
    id: 'emp.re.stopped_assuming',
    type: 'reaction',
    text: 'I have stopped assuming good intent, and I do not like who that makes me.',
    tags: ['trust'],
    weight: 4,
    conditions: { relationshipMax: { trust: 40 } },
  },
  {
    id: 'emp.re.second_time',
    type: 'reaction',
    text: 'This is the second time. I noticed the first time as well.',
    tags: ['trust'],
    weight: 3,
    conditions: { personalityMax: { patience: 55 } },
  },
  {
    id: 'emp.re.pretend_not_to_mind',
    type: 'reaction',
    text: 'I am past the point of pretending not to mind.',
    tags: ['doubt'],
    weight: 3,
    conditions: { personalityMin: { ego: 60 } },
  },
  {
    id: 'emp.re.can_work_with_no',
    type: 'reaction',
    text: 'If the answer is no, say it is no. I can work with no.',
    tags: ['direct'],
    weight: 4,
    conditions: { personalityMin: { directness: 65 } },
  },
  {
    id: 'emp.re.building_or_holding',
    type: 'reaction',
    text: 'I need to know whether I am building something here or holding something together.',
    tags: ['mission', 'doubt'],
    weight: 4,
    conditions: { motivations: ['mission', 'learning'] },
  },
  {
    id: 'emp.re.team_watching',
    type: 'reaction',
    text: 'Everyone on my team is watching how this gets handled. So am I.',
    tags: ['leadership', 'team'],
    weight: 3,
    conditions: { roles: ['executive', 'employee'] },
  },
  {
    id: 'emp.re.decision_rights',
    type: 'reaction',
    text: 'I do not need a title. I need the decision rights that go with the work.',
    tags: ['autonomy', 'promotion'],
    weight: 4,
    conditions: { motivations: ['autonomy', 'power'] },
  },
  { id: 'emp.re.cant_get_past', type: 'reaction', text: 'That is the part I cannot get past.', tags: ['doubt'], weight: 2 },
  { id: 'emp.re.worth_saying', type: 'reaction', text: 'Maybe none of this changes anything. It still felt worth saying.', tags: ['doubt'], weight: 2 },
]

const requests: readonly Fragment[] = [
  { id: 'emp.rq.path_plainly', type: 'request', text: 'Tell me plainly what my path here looks like.', tags: ['promotion', 'clarity'], weight: 4 },
  {
    id: 'emp.rq.thirty_minutes',
    type: 'request',
    text: 'I want thirty minutes this week, not a reply in a thread.',
    tags: ['clarity'],
    weight: 3,
    conditions: { personalityMin: { directness: 55 } },
  },
  {
    id: 'emp.rq.scope_in_writing',
    type: 'request',
    text: 'Give me the {role} scope in writing, or tell me it is not happening.',
    tags: ['promotion', 'clarity'],
    weight: 4,
    conditions: { requiresTags: ['promotion'] },
  },
  {
    id: 'emp.rq.two_headcount',
    type: 'request',
    text: 'Two more people, or we cut the roadmap. I can take either. I cannot take neither.',
    tags: ['workload', 'hiring'],
    weight: 4,
    conditions: { requiresTags: ['workload'] },
  },
  {
    id: 'emp.rq.own_the_area',
    type: 'request',
    text: 'Let me own {area} end to end.',
    tags: ['autonomy'],
    weight: 3,
    conditions: { motivations: ['autonomy', 'power', 'career_progression'] },
  },
  {
    id: 'emp.rq.comp_to_market',
    type: 'request',
    text: 'Bring my compensation to market. If we cannot, say so and I will decide what that means.',
    tags: ['compensation'],
    weight: 4,
    conditions: { requiresTags: ['compensation'] },
  },
  {
    id: 'emp.rq.in_the_room',
    type: 'request',
    text: 'I want to be in the room the next time a decision like this is made.',
    tags: ['status', 'communication'],
    weight: 4,
  },
  {
    id: 'emp.rq.say_plan_out_loud',
    type: 'request',
    text: 'Say out loud, to the whole team, what the plan actually is.',
    tags: ['strategy', 'communication'],
    weight: 4,
    conditions: { requiresTags: ['strategy'] },
  },
  {
    id: 'emp.rq.one_fixed_quarter',
    type: 'request',
    text: 'Give me one quarter with a roadmap that does not move and I will show you what this team can do.',
    tags: ['strategy'],
    weight: 3,
    conditions: { personalityMin: { optimism: 55 } },
  },
  {
    id: 'emp.rq.a_date',
    type: 'request',
    text: 'I want a date. Not a direction — a date.',
    tags: ['clarity'],
    weight: 3,
    conditions: { styles: ['analytical', 'direct', 'blunt'] },
  },
  {
    id: 'emp.rq.what_changed',
    type: 'request',
    text: 'Tell me what changed since week {mem_week}.',
    tags: ['callback', 'clarity'],
    weight: 4,
  },
  {
    id: 'emp.rq.role_gone',
    type: 'request',
    text: 'If the role is gone, I would rather hear that now than in six months.',
    tags: ['promotion', 'clarity'],
    weight: 3,
    conditions: { requiresTags: ['exec_hire'] },
  },
  {
    id: 'emp.rq.who_i_report_to',
    type: 'request',
    text: 'I want to know who I report to before it is announced to everyone else.',
    tags: ['exec_hire', 'clarity'],
    weight: 4,
    conditions: { requiresTags: ['exec_hire'] },
  },
  {
    id: 'emp.rq.refill_or_remove',
    type: 'request',
    text: 'Refill the roles we lost, or take something off the list. Either works.',
    tags: ['workload'],
    weight: 3,
    conditions: { requiresTags: ['workload'] },
  },
  {
    id: 'emp.rq.equity_refresh',
    type: 'request',
    text: 'Refresh my equity to reflect what the job actually became.',
    tags: ['compensation', 'equity'],
    weight: 3,
    conditions: { motivations: ['money', 'status'] },
  },
  {
    id: 'emp.rq.front_of_board',
    type: 'request',
    text: 'Put me in front of the board once. That is the whole ask.',
    tags: ['status'],
    weight: 3,
    conditions: { motivations: ['status', 'recognition', 'career_progression'] },
  },
  {
    id: 'emp.rq.back_me_publicly',
    type: 'request',
    text: 'Back me publicly on this, even if you take it apart with me privately.',
    tags: ['leadership', 'status'],
    weight: 3,
    conditions: { roles: ['executive'] },
  },
  {
    id: 'emp.rq.be_honest',
    type: 'request',
    text: 'Be honest with me about where this is going.',
    tags: ['clarity'],
    weight: 3,
    conditions: { styles: ['warm', 'cautious', 'enthusiastic'] },
  },
  {
    id: 'emp.rq.hire_someone_done_it',
    type: 'request',
    text: 'Let me hire one person who has done this before. I would rather learn it than guess it.',
    tags: ['hiring', 'learning'],
    weight: 3,
    conditions: { motivations: ['learning'] },
  },
  {
    id: 'emp.rq.decide',
    type: 'request',
    text: 'Decide. Either answer is survivable. This is not.',
    tags: ['clarity'],
    weight: 3,
    conditions: { styles: ['blunt', 'direct'], personalityMin: { directness: 70 } },
  },
  {
    id: 'emp.rq.tell_me_no_surprise',
    type: 'request',
    text: 'If something like this is coming again, tell me first. That is all.',
    tags: ['communication'],
    weight: 3,
  },
  {
    id: 'emp.rq.take_account',
    type: 'request',
    text: 'Let me take {segment} myself for a quarter.',
    tags: ['autonomy', 'customer'],
    weight: 2,
    conditions: { roles: ['employee', 'executive'] },
  },
]

const closings: readonly Fragment[] = [
  { id: 'emp.cl.signoff', type: 'closing', text: '— {firstName}', tags: ['signoff'], weight: 2, conditions: { styles: ['blunt', 'direct'] } },
  { id: 'emp.cl.hear_it_out', type: 'closing', text: "Whatever you decide, I'll hear it out.", tags: ['signoff'], weight: 3, conditions: { personalityMin: { patience: 55 } } },
  { id: 'emp.cl.rather_this_conversation', type: 'closing', text: "I'd rather have this conversation than the other one.", tags: ['signoff'], weight: 3 },
  { id: 'emp.cl.thanks_for_reading', type: 'closing', text: 'Thanks for reading all of that.', tags: ['signoff'], weight: 2, conditions: { styles: ['warm', 'formal', 'enthusiastic'] } },
  { id: 'emp.cl.no_drama', type: 'closing', text: 'That is it. No drama intended.', tags: ['signoff'], weight: 2, conditions: { personalityMax: { ego: 50 } } },
  { id: 'emp.cl.keep_doing_work', type: 'closing', text: "I'll keep doing the work in the meantime.", tags: ['signoff', 'loyalty'], weight: 3, conditions: { personalityMin: { loyalty: 60 } } },
  { id: 'emp.cl.when_you_have_time', type: 'closing', text: 'Let me know when you have time.', tags: ['signoff'], weight: 2, conditions: { styles: ['formal', 'cautious'] } },
  { id: 'emp.cl.around_all_week', type: 'closing', text: "I'm around all week.", tags: ['signoff'], weight: 2, conditions: { styles: ['warm', 'enthusiastic'] } },
  { id: 'emp.cl.hope_im_wrong', type: 'closing', text: 'I hope I am wrong about some of this.', tags: ['signoff'], weight: 2, conditions: { personalityMin: { optimism: 55 } } },
  { id: 'emp.cl.said_my_piece', type: 'closing', text: 'I have said my piece.', tags: ['signoff'], weight: 2, conditions: { styles: ['blunt'] } },
  { id: 'emp.cl.glad_i_said_it', type: 'closing', text: 'Whatever happens, I am glad I said it.', tags: ['signoff'], weight: 2 },
  { id: 'emp.cl.talk_me_out', type: 'closing', text: 'Happy to be talked out of any of this.', tags: ['signoff'], weight: 2, conditions: { styles: ['analytical'], relationshipMin: { trust: 55 } } },
  { id: 'emp.cl.reading_it_wrong', type: 'closing', text: 'Tell me I am reading it wrong and I will believe you.', tags: ['signoff', 'trust'], weight: 2, conditions: { relationshipMin: { trust: 65 } } },
  { id: 'emp.cl.no_answer_today', type: 'closing', text: 'No answer today is fine. No answer at all is not.', tags: ['signoff'], weight: 2, conditions: { personalityMin: { directness: 60 } } },
]

/**
 * Pool ids follow the '<audience>.<type>' convention from types.ts, which is what the composer's
 * shapes resolve against: a shape asking for a 'reaction' looks up 'employee.reaction'.
 */
export const EMPLOYEE_FRAGMENTS: FragmentLibrary = {
  'employee.opening': openings,
  'employee.context': contexts,
  'employee.memory': memoryCallbacks,
  'employee.reaction': reactions,
  'employee.request': requests,
  'employee.closing': closings,
}
