// Strategic Systems Expansion — the roadmap initiative pools, per sector.
//
// AUTHORED as game content (drafted by a six-agent content pass, curated by hand): impact is a
// BUDGET (≤6 points per item, 0–3 per axis) that strategic/effects.ts maps to bounded effects;
// weeks are base build time at REFERENCE velocity; segment multipliers are why targeting is a
// decision. Exactly one technical_debt item per sector pays the platform down. `quickPool`
// marks the four iconic items Quick Run exposes (brief §3.1); `lateStage` items appear from
// Series A. Do NOT put raw multipliers here — points only.
import type { RoadmapInitiativeDef } from './types'

export const ROADMAP_POOLS: Record<string, RoadmapInitiativeDef[]> = {
  saas: [
    { id: "saas-sso", sector: "saas", type: "customer_feature", name: "Enterprise SSO", blurb: "Procurement stops asking about SAML, but you maintain identity plumbing forever.", weeks: 5, impact: { monetization: 2, acquisition: 2 }, segmentImpact: { freelancers: 0.2, small_teams: 0.6, enterprise: 1.5 }, techDebtCreated: 2, quickPool: true, lateStage: true },
    { id: "saas-audit-logs", sector: "saas", type: "customer_feature", name: "Audit Logs", blurb: "Every action recorded; security reviews pass faster and nobody else notices.", weeks: 3, impact: { monetization: 2, retention: 1 }, segmentImpact: { freelancers: 0.2, small_teams: 0.5, enterprise: 1.5 }, techDebtCreated: 1, lateStage: true },
    { id: "saas-integrations", sector: "saas", type: "customer_feature", name: "Integrations", blurb: "Plug into the tools they already use \u2014 every connector is one more thing that breaks.", weeks: 5, impact: { acquisition: 2, retention: 2 }, segmentImpact: { freelancers: 0.9, small_teams: 1.4, enterprise: 0.7 }, techDebtCreated: 3, quickPool: true },
    { id: "saas-analytics", sector: "saas", type: "customer_feature", name: "Usage Analytics", blurb: "Customers see their own numbers, and admins find reasons to keep paying.", weeks: 4, impact: { retention: 2, monetization: 1 }, segmentImpact: { freelancers: 0.5, small_teams: 1.3, enterprise: 1.1 } },
    { id: "saas-role-permissions", sector: "saas", type: "customer_feature", name: "Role Permissions", blurb: "Who can do what, finally answered \u2014 the checkbox enterprise won't buy without.", weeks: 4, impact: { monetization: 1, retention: 1, productQuality: 1 }, segmentImpact: { freelancers: 0.2, small_teams: 0.9, enterprise: 1.5 }, techDebtCreated: 3, lateStage: true },
    { id: "saas-collaboration", sector: "saas", type: "customer_feature", name: "Real-Time Collaboration", blurb: "Whole teams in one document \u2014 leaving now means leaving together.", weeks: 6, impact: { retention: 2, acquisition: 1, productQuality: 1 }, segmentImpact: { freelancers: 0.4, small_teams: 1.5, enterprise: 0.8 }, techDebtCreated: 4, quickPool: true },
    { id: "saas-public-api", sector: "saas", type: "platform", name: "Public API", blurb: "Customers build on top of you, and ripping you out gets expensive.", weeks: 5, impact: { retention: 2, acquisition: 1, monetization: 1 }, segmentImpact: { freelancers: 0.6, small_teams: 1, enterprise: 1.4 }, techDebtCreated: 2 },
    { id: "saas-admin-controls", sector: "saas", type: "customer_feature", name: "Admin Controls", blurb: "One screen for seats, billing, and access \u2014 built for the buyer, not the user.", weeks: 3, impact: { monetization: 1, retention: 1, operatingEfficiency: 1 }, segmentImpact: { freelancers: 0.2, small_teams: 0.7, enterprise: 1.5 }, lateStage: true },
    { id: "saas-onboarding-redesign", sector: "saas", type: "growth_system", name: "Onboarding Redesign", blurb: "New signups hit the point of the product sooner, and fewer bounce on day one.", weeks: 4, impact: { acquisition: 2, retention: 1, productQuality: 1 }, segmentImpact: { freelancers: 1.5, small_teams: 1, enterprise: 0.3 }, quickPool: true },
    { id: "saas-platform-paydown", sector: "saas", type: "technical_debt", name: "Pay Down the Platform", blurb: "Six months of shortcuts unwound \u2014 nothing new ships, everything after ships faster.", weeks: 4, impact: { developerVelocity: 2, reliability: 1 }, segmentImpact: { freelancers: 0.8, small_teams: 1, enterprise: 1.1 }, techDebtReduced: 14 },
    { id: "saas-support-console", sector: "saas", type: "internal_system", name: "Support Console", blurb: "Tickets stop living in a shared inbox, and the same team handles twice the volume.", weeks: 3, impact: { operatingEfficiency: 2, retention: 1 }, segmentImpact: { freelancers: 1.4, small_teams: 1, enterprise: 0.4 } },
  ],
  social: [
    { id: "social-feed-ranking", sector: "social", type: "customer_feature", name: "Feed Ranking", blurb: "Ranked feeds keep people scrolling longer \u2014 and the ranking code keeps growing.", weeks: 5, impact: { retention: 2, productQuality: 2 }, segmentImpact: { casual_users: 1.3, creators: 1, brand_advertisers: 0.6 }, techDebtCreated: 4, quickPool: true },
    { id: "social-recommendations", sector: "social", type: "customer_feature", name: "For You Recommendations", blurb: "New users get shown accounts worth following before they get bored.", weeks: 5, impact: { acquisition: 1, retention: 2, productQuality: 1 }, segmentImpact: { casual_users: 1.1, creators: 1.3, brand_advertisers: 0.4 } },
    { id: "social-creator-studio", sector: "social", type: "customer_feature", name: "Creator Studio", blurb: "Analytics, scheduling, and drafts \u2014 the tools that make posting a job worth keeping.", weeks: 5, impact: { retention: 2, monetization: 1, productQuality: 1 }, segmentImpact: { casual_users: 0.4, creators: 1.5, brand_advertisers: 0.7 }, quickPool: true },
    { id: "social-messaging", sector: "social", type: "customer_feature", name: "Direct Messages", blurb: "Conversations stay in your app instead of finishing on someone else's.", weeks: 4, impact: { retention: 2, productQuality: 1 }, segmentImpact: { casual_users: 1.3, creators: 0.9, brand_advertisers: 0.3 }, quickPool: true },
    { id: "social-referral-loop", sector: "social", type: "growth_system", name: "Referral Loop", blurb: "Invites with a reward on both ends; cheap growth while the math holds.", weeks: 3, impact: { acquisition: 3 }, segmentImpact: { casual_users: 1.4, creators: 0.8, brand_advertisers: 0.2 }, techDebtCreated: 2, quickPool: true },
    { id: "social-sharing", sector: "social", type: "growth_system", name: "Share Everywhere", blurb: "One-tap cross-posting turns every creator's other audience into your funnel.", weeks: 3, impact: { acquisition: 2, retention: 1 }, segmentImpact: { casual_users: 1.1, creators: 1.4, brand_advertisers: 0.3 } },
    { id: "social-notifications", sector: "social", type: "growth_system", name: "Push Notifications", blurb: "Well-timed pings bring people back; badly timed ones teach them to uninstall.", weeks: 3, impact: { acquisition: 1, retention: 2 }, segmentImpact: { casual_users: 1.4, creators: 0.9, brand_advertisers: 0.2 }, techDebtCreated: 2 },
    { id: "social-moderation-desk", sector: "social", type: "internal_system", name: "Trust & Safety Desk", blurb: "Report queues and mod tooling keep the platform clean enough for brands to touch.", weeks: 4, impact: { productQuality: 1, reliability: 1, operatingEfficiency: 2 }, segmentImpact: { casual_users: 0.8, creators: 0.7, brand_advertisers: 1.5 } },
    { id: "social-ads-manager", sector: "social", type: "platform", name: "Ads Manager", blurb: "Self-serve campaigns, targeting, and reporting \u2014 the audience finally pays the bills.", weeks: 6, impact: { monetization: 3, acquisition: 1, operatingEfficiency: 1 }, segmentImpact: { casual_users: 0.2, creators: 0.6, brand_advertisers: 1.5 }, techDebtCreated: 4, lateStage: true },
    { id: "social-feed-pipeline-rebuild", sector: "social", type: "technical_debt", name: "Feed Pipeline Rebuild", blurb: "Rebuild the feed's plumbing now, or watch every future feature take twice as long.", weeks: 4, impact: { developerVelocity: 2, reliability: 1 }, segmentImpact: { casual_users: 1, creators: 1, brand_advertisers: 1 }, techDebtReduced: 14 },
  ],
  fintech: [
    { id: "fintech-fraud-detection", sector: "fintech", type: "customer_feature", name: "Fraud Detection", blurb: "Catches the bad transactions before they hit the ledger \u2014 and a few good ones with them.", weeks: 5, impact: { productQuality: 2, retention: 1, operatingEfficiency: 1 }, segmentImpact: { consumers: 1.3, smb_finance: 0.9, regulated_institutions: 1.2 }, techDebtCreated: 3, quickPool: true },
    { id: "fintech-kyc-automation", sector: "fintech", type: "internal_system", name: "KYC Automation", blurb: "Signups verify themselves in minutes instead of sitting in a queue; the review team shrinks to the weird cases.", weeks: 5, impact: { acquisition: 2, operatingEfficiency: 2 }, segmentImpact: { consumers: 1.4, smb_finance: 1, regulated_institutions: 0.5 }, techDebtCreated: 2 },
    { id: "fintech-transaction-controls", sector: "fintech", type: "customer_feature", name: "Transaction Controls", blurb: "Limits, freezes, and approval chains \u2014 finance teams sleep better and stay longer.", weeks: 4, impact: { retention: 2, productQuality: 1 }, segmentImpact: { consumers: 0.6, smb_finance: 1.5, regulated_institutions: 1 }, techDebtCreated: 1 },
    { id: "fintech-compliance-suite", sector: "fintech", type: "platform", name: "Compliance Suite", blurb: "Audit trails and regulatory reports that get you past procurement; nobody else will ever open them.", weeks: 6, impact: { acquisition: 2, monetization: 2 }, segmentImpact: { consumers: 0.2, smb_finance: 0.7, regulated_institutions: 1.5 }, techDebtCreated: 2, lateStage: true },
    { id: "fintech-reliability-hardening", sector: "fintech", type: "infrastructure", name: "Reliability Hardening", blurb: "Redundancy and failover, because in money an hour of downtime reads as gone for good.", weeks: 5, impact: { reliability: 3, retention: 1 }, segmentImpact: { consumers: 0.9, smb_finance: 1.2, regulated_institutions: 1.4 }, techDebtReduced: 5, quickPool: true },
    { id: "fintech-risk-engine", sector: "fintech", type: "platform", name: "Risk Engine", blurb: "Scores every account and transaction so you can price risk instead of eating it.", weeks: 6, impact: { monetization: 2, productQuality: 1, operatingEfficiency: 1 }, segmentImpact: { consumers: 0.7, smb_finance: 1.4, regulated_institutions: 1.1 }, techDebtCreated: 4 },
    { id: "fintech-account-management", sector: "fintech", type: "customer_feature", name: "Account Management", blurb: "Statements, cards, and settings people can find on their own \u2014 fewer tickets, fewer quiet exits.", weeks: 3, impact: { retention: 2, productQuality: 1 }, segmentImpact: { consumers: 1.3, smb_finance: 1.1, regulated_institutions: 0.5 }, techDebtCreated: 1, quickPool: true },
    { id: "fintech-ledger-rebuild", sector: "fintech", type: "technical_debt", name: "Ledger Rebuild", blurb: "Rebuild the money core on real double-entry before the reconciliation scripts become the product.", weeks: 5, impact: { developerVelocity: 2, reliability: 1 }, segmentImpact: { consumers: 0.9, smb_finance: 1, regulated_institutions: 1.2 }, techDebtReduced: 14 },
    { id: "fintech-dispute-desk", sector: "fintech", type: "internal_system", name: "Dispute Resolution Desk", blurb: "One queue and a playbook for chargebacks, instead of a shared inbox and a prayer.", weeks: 3, impact: { operatingEfficiency: 2, retention: 1 }, segmentImpact: { consumers: 1.4, smb_finance: 0.9, regulated_institutions: 0.4 } },
    { id: "fintech-instant-payments", sector: "fintech", type: "customer_feature", name: "Instant Payments", blurb: "Money that lands in seconds is the demo that sells itself \u2014 along with the rail fees that come with it.", weeks: 5, impact: { acquisition: 2, productQuality: 1, retention: 1 }, segmentImpact: { consumers: 1.4, smb_finance: 1.1, regulated_institutions: 0.5 }, techDebtCreated: 3, quickPool: true },
    { id: "fintech-referral-payouts", sector: "fintech", type: "growth_system", name: "Referral Payouts", blurb: "Pay users cash to bring their friends; cheap growth until the fraudsters find it.", weeks: 3, impact: { acquisition: 3 }, segmentImpact: { consumers: 1.5, smb_finance: 0.6, regulated_institutions: 0.2 }, techDebtCreated: 2 },
  ],
  devtools: [
    { id: "devtools-sdk", sector: "devtools", type: "customer_feature", name: "Client SDKs", blurb: "Devs install in one line; you maintain six language libraries forever.", weeks: 4, impact: { acquisition: 2, productQuality: 1, retention: 1 }, segmentImpact: { individual_devs: 1.4, startup_eng: 1.1, enterprise_eng: 0.6 }, techDebtCreated: 3, quickPool: true },
    { id: "devtools-public-api", sector: "devtools", type: "platform", name: "Public API v1", blurb: "Everything becomes scriptable, and every endpoint becomes a promise you can't break later.", weeks: 5, impact: { acquisition: 1, productQuality: 2, retention: 1 }, segmentImpact: { individual_devs: 1, startup_eng: 1.3, enterprise_eng: 0.9 }, techDebtCreated: 4 },
    { id: "devtools-integrations", sector: "devtools", type: "customer_feature", name: "CI/CD Integrations", blurb: "Meet teams inside GitHub and their pipeline \u2014 each integration a surface that can break on someone else's release day.", weeks: 4, impact: { acquisition: 2, retention: 2 }, segmentImpact: { individual_devs: 0.7, startup_eng: 1.5, enterprise_eng: 0.9 }, techDebtCreated: 3, quickPool: true },
    { id: "devtools-docs", sector: "devtools", type: "customer_feature", name: "Docs Overhaul", blurb: "Good docs close deals you never see and halve the support queue.", weeks: 3, impact: { acquisition: 2, retention: 1 }, segmentImpact: { individual_devs: 1.5, startup_eng: 1, enterprise_eng: 0.5 }, quickPool: true },
    { id: "devtools-onboarding", sector: "devtools", type: "growth_system", name: "Five-Minute Quickstart", blurb: "First success in five minutes or they close the tab and never come back.", weeks: 3, impact: { acquisition: 3, retention: 1 }, segmentImpact: { individual_devs: 1.5, startup_eng: 1.1, enterprise_eng: 0.3 }, techDebtCreated: 1, quickPool: true },
    { id: "devtools-observability", sector: "devtools", type: "customer_feature", name: "Usage Observability", blurb: "Customers see what's slow, what's failing, and why \u2014 and teams that can see stay.", weeks: 5, impact: { productQuality: 2, retention: 1, monetization: 1 }, segmentImpact: { individual_devs: 0.4, startup_eng: 1.2, enterprise_eng: 1.4 }, techDebtCreated: 2 },
    { id: "devtools-reliability", sector: "devtools", type: "infrastructure", name: "Five Nines Push", blurb: "Nobody tweets about uptime, but everybody churns over the outage.", weeks: 5, impact: { reliability: 3, retention: 1 }, segmentImpact: { individual_devs: 0.5, startup_eng: 1, enterprise_eng: 1.5 }, techDebtReduced: 6 },
    { id: "devtools-platform-paydown", sector: "devtools", type: "technical_debt", name: "Pay Down the Platform", blurb: "No new features ship this month so that every future one ships faster.", weeks: 4, impact: { developerVelocity: 2, reliability: 1 }, segmentImpact: { individual_devs: 0.9, startup_eng: 1, enterprise_eng: 1.1 }, techDebtReduced: 14 },
    { id: "devtools-support-desk", sector: "devtools", type: "internal_system", name: "Support Triage System", blurb: "Tickets get routed and deflected before they pile up, and the team stops firefighting inboxes.", weeks: 3, impact: { operatingEfficiency: 2, retention: 1 }, segmentImpact: { individual_devs: 1.3, startup_eng: 1, enterprise_eng: 0.6 } },
    { id: "devtools-enterprise-sso", sector: "devtools", type: "customer_feature", name: "SSO & Audit Logs", blurb: "The checkbox that unlocks procurement \u2014 and means nothing to anyone else.", weeks: 6, impact: { monetization: 3, acquisition: 1 }, segmentImpact: { individual_devs: 0.2, startup_eng: 0.6, enterprise_eng: 1.5 }, techDebtCreated: 3, lateStage: true },
    { id: "devtools-self-serve-billing", sector: "devtools", type: "growth_system", name: "Self-Serve Billing", blurb: "Cards go in without a sales call; revenue starts while you sleep.", weeks: 4, impact: { monetization: 2, acquisition: 1 }, segmentImpact: { individual_devs: 1.2, startup_eng: 1.3, enterprise_eng: 0.3 }, techDebtCreated: 2 },
  ],
  ecommerce: [
    { id: "ecommerce-one-click-checkout", sector: "ecommerce", type: "customer_feature", name: "One-Click Checkout", blurb: "Carts stop dying at the payment page, and every store's conversion ticks up.", weeks: 4, impact: { monetization: 2, acquisition: 1, productQuality: 1 }, segmentImpact: { individual_sellers: 1.3, growing_brands: 1, enterprise_retail: 0.6 }, techDebtCreated: 3, quickPool: true },
    { id: "ecommerce-storefront-search", sector: "ecommerce", type: "customer_feature", name: "Storefront Search", blurb: "Shoppers find the thing instead of leaving; matters more the bigger the catalog.", weeks: 3, impact: { productQuality: 2, retention: 1 }, segmentImpact: { individual_sellers: 0.6, growing_brands: 1.2, enterprise_retail: 1.2 }, techDebtCreated: 2, quickPool: true },
    { id: "ecommerce-recommendations", sector: "ecommerce", type: "customer_feature", name: "Product Recommendations", blurb: "Bigger baskets, but only for stores with enough traffic to feed the model.", weeks: 5, impact: { monetization: 2, retention: 1, productQuality: 1 }, segmentImpact: { individual_sellers: 0.4, growing_brands: 1.4, enterprise_retail: 1.1 }, techDebtCreated: 3, quickPool: true },
    { id: "ecommerce-loyalty-rewards", sector: "ecommerce", type: "customer_feature", name: "Loyalty & Rewards", blurb: "Points and perks that turn one-time buyers into reorders.", weeks: 3, impact: { retention: 2, monetization: 1 }, segmentImpact: { individual_sellers: 0.6, growing_brands: 1.4, enterprise_retail: 0.8 }, techDebtCreated: 2, quickPool: true },
    { id: "ecommerce-fulfillment-integrations", sector: "ecommerce", type: "platform", name: "Fulfillment Integrations", blurb: "Orders flow straight to carriers and 3PLs; merchants stop retyping addresses.", weeks: 6, impact: { retention: 2, reliability: 1, acquisition: 1 }, segmentImpact: { individual_sellers: 0.4, growing_brands: 1.3, enterprise_retail: 1.4 }, techDebtCreated: 4 },
    { id: "ecommerce-returns-portal", sector: "ecommerce", type: "customer_feature", name: "Returns Portal", blurb: "Returns become a self-serve form instead of a week of support email.", weeks: 3, impact: { retention: 1, productQuality: 1, operatingEfficiency: 1 }, segmentImpact: { individual_sellers: 0.5, growing_brands: 1.2, enterprise_retail: 1.3 }, techDebtCreated: 1 },
    { id: "ecommerce-catalog-manager", sector: "ecommerce", type: "customer_feature", name: "Bulk Catalog Manager", blurb: "Import and edit a thousand SKUs without a spreadsheet accident.", weeks: 4, impact: { productQuality: 2, acquisition: 1 }, segmentImpact: { individual_sellers: 0.7, growing_brands: 1.1, enterprise_retail: 1.4 }, techDebtCreated: 2 },
    { id: "ecommerce-instant-storefronts", sector: "ecommerce", type: "growth_system", name: "Instant Storefronts", blurb: "A store you can open in an afternoon; keeping the seller is a separate problem.", weeks: 4, impact: { acquisition: 3, productQuality: 1 }, segmentImpact: { individual_sellers: 1.5, growing_brands: 0.7, enterprise_retail: 0.2 }, techDebtCreated: 2 },
    { id: "ecommerce-enterprise-suite", sector: "ecommerce", type: "platform", name: "Enterprise Integrations Suite", blurb: "ERP connectors and an SLA to sign \u2014 the price of admission for the big logos.", weeks: 7, impact: { monetization: 2, acquisition: 2, reliability: 1 }, segmentImpact: { individual_sellers: 0.2, growing_brands: 0.5, enterprise_retail: 1.5 }, techDebtCreated: 5, lateStage: true },
    { id: "ecommerce-order-pipeline-paydown", sector: "ecommerce", type: "technical_debt", name: "Order Pipeline Rebuild", blurb: "The order pipeline stops being the place where new features go to die.", weeks: 4, impact: { developerVelocity: 2, reliability: 1 }, segmentImpact: { individual_sellers: 0.8, growing_brands: 1, enterprise_retail: 1.2 }, techDebtReduced: 14 },
    { id: "ecommerce-merchant-ops-console", sector: "ecommerce", type: "internal_system", name: "Merchant Ops Console", blurb: "Support sees every merchant's mess in one place and closes tickets before they churn.", weeks: 3, impact: { operatingEfficiency: 2, retention: 1 }, segmentImpact: { individual_sellers: 1.4, growing_brands: 0.9, enterprise_retail: 0.5 } },
  ],
  aiml: [
    { id: "aiml-model-routing", sector: "aiml", type: "customer_feature", name: "Smart Model Routing", blurb: "One endpoint sends each request to the cheapest model that is good enough; customers' bills shrink and they notice.", weeks: 4, impact: { productQuality: 2, retention: 2 }, segmentImpact: { indie_hackers: 0.8, ai_startups: 1.4, enterprise_ml: 0.7 }, techDebtCreated: 3, quickPool: true },
    { id: "aiml-eval-harness", sector: "aiml", type: "customer_feature", name: "Eval Harness", blurb: "Lets teams prove a prompt or model swap didn't break production before they ship it.", weeks: 4, impact: { productQuality: 2, retention: 2 }, segmentImpact: { indie_hackers: 0.5, ai_startups: 1.4, enterprise_ml: 1 }, techDebtCreated: 2, quickPool: true },
    { id: "aiml-inference-optimisation", sector: "aiml", type: "infrastructure", name: "Inference Speed Pass", blurb: "Batching and cache work that cuts latency in half \u2014 and your GPU bill with it.", weeks: 6, impact: { productQuality: 2, operatingEfficiency: 2, reliability: 1 }, segmentImpact: { indie_hackers: 1.1, ai_startups: 1.3, enterprise_ml: 0.9 }, techDebtCreated: 4, quickPool: true },
    { id: "aiml-observability", sector: "aiml", type: "customer_feature", name: "LLM Observability", blurb: "Traces, token spend, and failure rates per request \u2014 the first tab customers open when production misbehaves.", weeks: 4, impact: { retention: 2, productQuality: 1, monetization: 1 }, segmentImpact: { indie_hackers: 0.6, ai_startups: 1.2, enterprise_ml: 1.3 }, techDebtCreated: 2 },
    { id: "aiml-security-pack", sector: "aiml", type: "customer_feature", name: "Enterprise Security Pack", blurb: "SOC 2, SSO, and VPC deployment \u2014 the checklist that turns security review from a wall into a door.", weeks: 6, impact: { monetization: 2, acquisition: 2 }, segmentImpact: { indie_hackers: 0.2, ai_startups: 0.6, enterprise_ml: 1.5 }, techDebtCreated: 2, lateStage: true },
    { id: "aiml-orchestration", sector: "aiml", type: "platform", name: "Agent Orchestration", blurb: "Chains, retries, and human handoffs as a first-class product; powerful, sprawling, and hard to keep simple.", weeks: 7, impact: { productQuality: 2, retention: 2, acquisition: 1 }, segmentImpact: { indie_hackers: 0.7, ai_startups: 1.4, enterprise_ml: 0.9 }, techDebtCreated: 6, lateStage: true },
    { id: "aiml-sdk-cli", sector: "aiml", type: "customer_feature", name: "SDKs & CLI", blurb: "A five-minute quickstart in every language; the docs do the selling.", weeks: 3, impact: { acquisition: 2, productQuality: 1 }, segmentImpact: { indie_hackers: 1.5, ai_startups: 1.1, enterprise_ml: 0.4 }, techDebtCreated: 1 },
    { id: "aiml-playground", sector: "aiml", type: "growth_system", name: "Free Playground", blurb: "Try any model in the browser without a credit card; signups spike, most never pay.", weeks: 3, impact: { acquisition: 3 }, segmentImpact: { indie_hackers: 1.5, ai_startups: 0.9, enterprise_ml: 0.3 }, techDebtCreated: 1, quickPool: true },
    { id: "aiml-serving-stack-debt", sector: "aiml", type: "technical_debt", name: "Pay Down the Serving Stack", blurb: "Rebuild the launch-week serving stack properly; nothing new ships this month, everything ships faster after.", weeks: 5, impact: { developerVelocity: 2, reliability: 1 }, segmentImpact: { indie_hackers: 0.6, ai_startups: 1, enterprise_ml: 1.2 }, techDebtReduced: 14 },
    { id: "aiml-gpu-capacity-desk", sector: "aiml", type: "internal_system", name: "GPU Capacity Desk", blurb: "Internal forecasting that buys GPU hours before the crunch, not during it.", weeks: 4, impact: { operatingEfficiency: 2, reliability: 1 }, segmentImpact: { indie_hackers: 0.7, ai_startups: 1, enterprise_ml: 1.2 }, techDebtCreated: 1 },
  ],
}

export const roadmapPool = (sector: string): RoadmapInitiativeDef[] => ROADMAP_POOLS[sector] ?? ROADMAP_POOLS.saas
export const roadmapDef = (sector: string, id: string): RoadmapInitiativeDef | undefined =>
  roadmapPool(sector).find((i) => i.id === id)
